# APRENDER SOBRE LISTAS
# APRENDER SOBRE TUPLAS
# APLICABILIDADE DE LISTAS E TUPLAS
# 1. COMO CRIAR UMA LISTA
# 2. MANIPULAR LISTAS
# 3. REALIZAR OPERACOES COM LISTAS
# 4. O QUE E UMA TUPLA
# 5. COMO INTERAGIR COM TUPLAS
# 6. CONVERSOES DE LISTAS E TUPLAS

# CRIAR UMA LISTA DE INTEIROS
#lista = [1, 3, 5, 7]
lista_animal = ['cahorro', 'gato', 'elefante']
#print(lista)
print(lista_animal[1])


