# 1. APRENDER A UTLIZACAO DE METODOS E FUNCOES NO PYTHON
# 2. APRENDER A UTILIZAÇÃO DE CLASSES
# 3. ENTENDER OS MOTIVOS PARA SE USAR METODOS, FUNCOES E CLASSES
# - O QUE SAO METODOS E FUNCOES
# - COMO DECLARAR METODOS E FUNCOES
# - VANTAGENS DE SE UTILIZAR METODOS E FUNCOES
# - COMO IMPLEMENTAR CLASS ;
# - VANTAGENS DE SE UTILIZAR CLASSES

#POR CONVENÇÃO:
#NO PYTHON METODO É TUDO QUE NAO RETORNA VALOR
# FUNCAO É TUDO QUE RETORNA VALOR
# NO PYTHON O METODO DE CHAMA DEFINICAO (def)

def soma(a, b) :
    return a + b

def subtracao(a, b) :
    return a - b

print(soma(1, 2))
print(soma(3,4))
print(subtracao(5, 2))
print(subtracao(9, 2))
